"""The manuscript's verified numbers, and the manuscript as files (CLAUDE.md: the writer sees only
verified results; gains are computed deterministically from the result files).

The engine writes `results.json` and `results.tex` into every manuscript version from the
harness's result files. The drafter `\\input{results}`s the tables and writes the prose; it never
types a number into a table. Test-set numbers enter only at export, once (U-TOP-5).
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Optional

from ..harness import sandbox as sbx
from ..harness.harness import gain


def latex_escape(text: Any) -> str:
    s = str(text)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def _row(result: Optional[dict]) -> dict:
    r = result or {}
    return {"status": r.get("status"), "mean": r.get("mean"), "std": r.get("std"),
            "n_seeds": r.get("n_seeds"), "split": r.get("split")}


def payload(task, base, core, ablations: list[dict], rebuttals: list[dict],
            test: Optional[dict] = None) -> dict:
    """Every number a manuscript may state, from result files only."""
    out = {
        "metric": task.metric_name, "direction": task.direction,
        "note": ("Validation numbers (the `full` split), mean and sample standard deviation over "
                 "seeds; computed by the engine's locked harness, not by the method's code."),
        "main": [{"method": "Baseline (reproduced)", **_row(base.full)},
                 {"method": f"Proposed: {core.idea.get('title', core.id)}", **_row(core.result)}],
        "gain_over_baseline": gain(core.result, base.full),
        "ablations": [{"id": a["id"], "component": a["plan"].get("component", ""),
                       "change": a["plan"].get("change", ""), **_row(a["result"]),
                       "delta_vs_full_method": a.get("delta_vs_full_method")} for a in ablations],
        "rebuttal": [{"id": r["id"], "concern": r["task"].get("concern", ""),
                      "experiment": r["task"].get("experiment", ""), **_row(r["result"]),
                      "delta_vs_full_method": r.get("delta_vs_full_method")} for r in rebuttals],
    }
    if test is not None:
        out["test"] = test
    return out


def _fmt(row: dict, digits: int = 4) -> str:
    if row.get("status") != "ok" or row.get("mean") is None:
        return "failed"
    n = row.get("n_seeds") or 1
    return f"{row['mean']:.{digits}f} $\\pm$ {row['std']:.{digits}f} ({n} seed{'s' if n != 1 else ''})"


def _delta(d: Optional[float], digits: int = 4) -> str:
    return "--" if d is None else f"{d:+.{digits}f}"


def results_tex(p: dict) -> str:
    m = latex_escape(p["metric"])
    better = "higher" if p["direction"] == "max" else "lower"
    lines = [f"% Generated by the engine from the harness's result files. Do not edit by hand.",
             r"\begin{table}[t]", r"\centering",
             f"\\caption{{Main results on the validation set: {m}, {better} is better. "
             f"Mean $\\pm$ standard deviation over seeds, computed by the evaluation harness.}}",
             r"\label{tab:main}", r"\begin{tabular}{lc}", r"\toprule", f"Method & {m} \\\\", r"\midrule"]
    for row in p["main"]:
        lines.append(f"{latex_escape(row['method'])} & {_fmt(row)} \\\\")
    lines += [r"\midrule", f"Gain over the reproduced baseline & {_delta(p['gain_over_baseline'])} \\\\",
              r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p["ablations"]:
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Ablations on the validation set: each row changes one component of "
                  f"the proposed method. $\\Delta$ is the change in {m} against the full method.}}",
                  r"\label{tab:ablation}", r"\begin{tabular}{p{0.55\linewidth}cc}", r"\toprule",
                  f"Ablation & {m} & $\\Delta$ \\\\", r"\midrule"]
        for a in p["ablations"]:
            label = latex_escape(f"{a['id']}: {a['component']}. {a['change']}")
            lines.append(f"{label} & {_fmt(a)} & {_delta(a['delta_vs_full_method'])} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p["rebuttal"]:
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Additional experiments requested in review, on the validation set. "
                  f"$\\Delta$ is the change in {m} against the full method.}}",
                  r"\label{tab:rebuttal}", r"\begin{tabular}{p{0.55\linewidth}cc}", r"\toprule",
                  f"Experiment & {m} & $\\Delta$ \\\\", r"\midrule"]
        for r in p["rebuttal"]:
            label = latex_escape(f"{r['id']}: {r['experiment']}")
            lines.append(f"{label} & {_fmt(r)} & {_delta(r['delta_vs_full_method'])} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p.get("test"):
        t = p["test"]
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Held-out test set, evaluated once, after every decision of the "
                  f"research loop was taken: {m}, mean $\\pm$ standard deviation over seeds.}}",
                  r"\label{tab:test}", r"\begin{tabular}{lc}", r"\toprule", f"Method & {m} \\\\", r"\midrule",
                  f"Baseline (reproduced) & {_fmt(t['baseline'])} \\\\",
                  f"Proposed & {_fmt(t['proposed'])} \\\\", r"\midrule",
                  f"Gain & {_delta(t.get('gain'))} \\\\", r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def write_results(folder: Path, p: dict) -> None:
    import json
    (folder / "results.json").write_text(json.dumps(p, indent=1, default=str))
    (folder / "results.tex").write_text(results_tex(p))


_INPUT = re.compile(r"\\input\{results(\.tex)?\}")


def manuscript_text(folder: Path) -> str:
    """The manuscript as a reviewer reads it: main.tex with the results tables inlined."""
    main = folder / "main.tex"
    if not main.exists():
        return "(no manuscript: main.tex is missing)"
    text = main.read_text(errors="replace")
    tables = (folder / "results.tex").read_text() if (folder / "results.tex").exists() else ""
    text = _INPUT.sub(lambda _: tables, text)
    bib = folder / "references.bib"
    if bib.exists():
        text += "\n\n% ===== references.bib =====\n" + bib.read_text(errors="replace")
    return text


def compile_pdf(folder: Path, build: Path, denied: list[Path], allow_unsandboxed: bool,
                protected: tuple[Path, ...] = ()) -> dict:
    """Best effort: latexmk into a separate build directory, sandboxed, no network."""
    exe = shutil.which("latexmk") or ("/Library/TeX/texbin/latexmk" if Path("/Library/TeX/texbin/latexmk").exists() else None)
    if exe is None:
        return {"ok": False, "error": "latexmk is not installed"}
    build.mkdir(parents=True, exist_ok=True)
    policy = sbx.SandboxPolicy.build(writable=[build], readonly=[folder], denied=denied,
                                     protected=protected, network=False)
    env = {"PATH": os.pathsep.join([str(Path(exe).parent), "/usr/bin", "/bin"]), "HOME": str(build),
           "TEXMFVAR": str(build / "texmf-var"), "TMPDIR": str(build), "LANG": "en_US.UTF-8"}
    argv = sbx.wrap([exe, "-pdf", "-interaction=nonstopmode", "-halt-on-error", f"-outdir={build}", "main.tex"],
                    policy, allow_unsandboxed)
    try:
        r = subprocess.run(argv, cwd=str(folder), env=env, capture_output=True, text=True, timeout=240)
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "latexmk timed out"}
    pdf = build / "main.pdf"
    if r.returncode == 0 and pdf.exists():
        return {"ok": True, "pdf": str(pdf)}
    return {"ok": False, "error": (r.stdout + r.stderr)[-1500:]}
