"""The manuscript's verified numbers, and the manuscript as files (CLAUDE.md: the writer sees only
verified results; gains are computed deterministically from the result files).

The engine writes `results.json` and `results.tex` into every manuscript version from the
harness's result files. The drafter `\\input{results}`s the tables and writes the prose; it never
types a number into a table. Test-set numbers enter only at export, once (U-TOP-5).

A writer CAN edit the copy of `results.tex` in its version, so no reader trusts that copy: a
reviewer reads the manuscript with the tables regenerated from the result files (`manuscript_text`
with `tables`), the PDF is built against a regenerated copy, and an edited copy is an audit finding
(integrity review 2026-10-02, finding 5). Numbers in the prose are checked against the results by
`unverified_numbers` (finding 4).
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Iterable, Optional

from ..harness import sandbox as sbx
from ..harness.harness import gain


def latex_escape(text: Any) -> str:
    s = str(text)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def _row(result: Optional[dict]) -> dict:
    r = result or {}
    return {"status": r.get("status"), "mean": r.get("mean"), "std": r.get("std"),
            "n_seeds": r.get("n_seeds"), "split": r.get("split"),
            "result_key": r.get("key"), "commit": r.get("commit")}


def payload(task, base, core, ablations: list[dict], rebuttals: list[dict],
            test: Optional[dict] = None) -> dict:
    """Every number a manuscript may state, from result files only, each traceable to its
    result file (`result_key`) and the code version that produced it (`commit`)."""
    out = {
        "metric": task.metric_name, "direction": task.direction,
        "note": ("Generated by the engine from the harness's result files; never edited by hand. "
                 "Validation numbers (the `full` split), mean and sample standard deviation over "
                 "seeds; computed by the engine's locked harness, not by the method's code."),
        "main": [{"method": "Baseline (reproduced)", **_row(base.full)},
                 {"method": f"Proposed: {core.idea.get('title', core.id)}", **_row(core.result)}],
        "gain_over_baseline": gain(core.result, base.full),
        "ablations": [{"id": a["id"], "component": a["plan"].get("component", ""),
                       "change": a["plan"].get("change", ""), **_row(a["result"]),
                       "delta_vs_full_method": a.get("delta_vs_full_method")} for a in ablations],
        "rebuttal": [{"id": r["id"], "concern": r["task"].get("concern", ""),
                      "experiment": r["task"].get("experiment", ""), **_row(r["result"]),
                      "delta_vs_full_method": r.get("delta_vs_full_method")} for r in rebuttals],
    }
    if test is not None:
        out["test"] = test
    return out


def _fmt(row: dict, digits: int = 4) -> str:
    if row.get("status") != "ok" or row.get("mean") is None:
        return "failed"
    n = row.get("n_seeds") or 1
    return f"{row['mean']:.{digits}f} $\\pm$ {row['std']:.{digits}f} ({n} seed{'s' if n != 1 else ''})"


def _delta(d: Optional[float], digits: int = 4) -> str:
    return "--" if d is None else f"{d:+.{digits}f}"


def _short(text: str, n: int = 160) -> str:
    text = " ".join(str(text).split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def results_tex(p: dict) -> str:
    m = latex_escape(p["metric"])
    better = "higher" if p["direction"] == "max" else "lower"
    lines = [r"\begin{table}[t]", r"\centering",
             f"\\caption{{Main results on the validation set: {m}, {better} is better. "
             f"Mean $\\pm$ standard deviation over seeds, computed by the evaluation harness.}}",
             r"\label{tab:main}", r"\begin{tabular}{lc}", r"\toprule", f"Method & {m} \\\\", r"\midrule"]
    for row in p["main"]:
        lines.append(f"{latex_escape(row['method'])} & {_fmt(row)} \\\\")
    lines += [r"\midrule", f"Gain over the reproduced baseline & {_delta(p['gain_over_baseline'])} \\\\",
              r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p["ablations"]:
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Ablations on the validation set: each row removes or replaces one "
                  f"component of the proposed method. $\\Delta$ is the change in {m} against the "
                  f"full method.}}",
                  r"\label{tab:ablation}", r"\begin{tabular}{p{0.55\linewidth}cc}", r"\toprule",
                  f"Component removed or replaced & {m} & $\\Delta$ \\\\", r"\midrule"]
        for a in p["ablations"]:
            label = latex_escape(f"{a['id']}: {_short(a['component'])}")
            lines.append(f"{label} & {_fmt(a)} & {_delta(a['delta_vs_full_method'])} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p["rebuttal"]:
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Supplementary experiments on the validation set. $\\Delta$ is the "
                  f"change in {m} against the full method.}}",
                  r"\label{tab:rebuttal}", r"\begin{tabular}{p{0.55\linewidth}cc}", r"\toprule",
                  f"Experiment & {m} & $\\Delta$ \\\\", r"\midrule"]
        for i, r in enumerate(p["rebuttal"], 1):
            label = latex_escape(f"S{i}: {_short(r['experiment'])}")
            lines.append(f"{label} & {_fmt(r)} & {_delta(r['delta_vs_full_method'])} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if p.get("test"):
        t = p["test"]
        lines += ["", r"\begin{table}[t]", r"\centering",
                  f"\\caption{{Held-out test set, evaluated once, after every decision of the "
                  f"research loop was taken: {m}, mean $\\pm$ standard deviation over seeds.}}",
                  r"\label{tab:test}", r"\begin{tabular}{p{0.55\linewidth}c}", r"\toprule",
                  f"Method & {m} \\\\", r"\midrule",
                  f"Baseline (reproduced) & {_fmt(t['baseline'])} \\\\",
                  f"Proposed & {_fmt(t['proposed'])} \\\\"]
        for v in t.get("variants") or []:
            lines.append(f"{latex_escape(v['id'] + ': ' + _short(v.get('label', ''), 120))} & {_fmt(v)} \\\\")
        lines += [r"\midrule", f"Gain of the proposed method & {_delta(t.get('gain'))} \\\\",
                  r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def write_results(folder: Path, p: dict) -> None:
    (folder / "results.json").write_text(json.dumps(p, indent=1, default=str))
    (folder / "results.tex").write_text(results_tex(p))


def tables_edited(folder: Path, p: dict) -> bool:
    """Does the version's copy of the engine's tables differ from the result files?"""
    f = folder / "results.tex"
    return f.exists() and f.read_text() != results_tex(p)


_INPUT = re.compile(r"\\input\{results(\.tex)?\}")
_COMMENT = re.compile(r"(?<!\\)%.*$", re.M)


def strip_comments(tex: str) -> str:
    return _COMMENT.sub("", tex)


def manuscript_text(folder: Path, tables: Optional[str] = None) -> str:
    """The manuscript as a reviewer reads it: main.tex without TeX comments, with the results
    tables inlined. `tables`: the engine's own tables, regenerated from the result files; without
    it the version's copy is used (only for versions no writer has touched since)."""
    main = folder / "main.tex"
    if not main.exists():
        return "(no manuscript: main.tex is missing)"
    text = strip_comments(main.read_text(errors="replace"))
    if tables is None:
        tables = (folder / "results.tex").read_text() if (folder / "results.tex").exists() else ""
    text = _INPUT.sub(lambda _: tables, text)
    bib = folder / "references.bib"
    if bib.exists():
        text += "\n\n===== references.bib =====\n" + bib.read_text(errors="replace")
    return text


# ---- numbers in the prose ---------------------------------------------------------------------
_NUMBER = re.compile(r"(?<![\w.])(\d+\.\d{2,})(?![\w.])(\s*\\?%)?")


def _values(obj: Any) -> Iterable[float]:
    if isinstance(obj, bool):
        return
    if isinstance(obj, (int, float)):
        yield float(obj)
    elif isinstance(obj, dict):
        for v in obj.values():
            yield from _values(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _values(v)


def unverified_numbers(folder: Path, p: dict, context: str = "") -> list[str]:
    """Decimals in main.tex's prose that are no value of the results (to the decimals written,
    as a fraction or a percentage, with or without sign) and do not occur in `context` (the task's
    paper and the method's description, where hyperparameters come from). A number of the paper
    should come from the engine's results; one computed by the writer is flagged."""
    main = folder / "main.tex"
    if not main.exists():
        return []
    prose = _INPUT.sub("", strip_comments(main.read_text(errors="replace")))
    values = list(_values(p))
    known_text = set(m.group(1) for m in _NUMBER.finditer(context))
    flagged = []
    for m in _NUMBER.finditer(prose):
        token, pct = m.group(1), bool(m.group(2))
        if token in known_text:
            continue
        x, d = float(token), len(token.split(".")[1])
        candidates = [abs(v) * (100 if pct else 1) for v in values]
        if not pct:
            candidates += [abs(v) * 100 for v in values]
        if any(abs(round(c, d) - x) < 10 ** (-d) / 2 + 1e-12 for c in candidates):
            continue
        flagged.append(token + ("%" if pct else ""))
    return sorted(set(flagged))


# ---- the PDF ----------------------------------------------------------------------------------
def compile_pdf(folder: Path, build: Path, policy: sbx.SandboxPolicy, allow_unsandboxed: bool,
                tables: Optional[str] = None) -> dict:
    """Best effort: latexmk into a separate build directory, sandboxed, no network. With
    `tables`, the build reads the engine's regenerated results.tex, never the version's copy."""
    exe = shutil.which("latexmk") or ("/Library/TeX/texbin/latexmk" if Path("/Library/TeX/texbin/latexmk").exists() else None)
    if exe is None:
        return {"ok": False, "error": "latexmk is not installed"}
    build.mkdir(parents=True, exist_ok=True)
    texinputs = ""
    if tables is not None:
        engine_tables = build / "engine-tables"
        engine_tables.mkdir(exist_ok=True)
        (engine_tables / "results.tex").write_text(tables)
        texinputs = f"{engine_tables}{os.pathsep}"          # searched before the version's own copy
    env = {"PATH": os.pathsep.join([str(Path(exe).parent), "/usr/bin", "/bin"]), "HOME": str(build),
           "TEXMFVAR": str(build / "texmf-var"), "TMPDIR": str(build), "LANG": "en_US.UTF-8"}
    if texinputs:
        env["TEXINPUTS"] = texinputs
    argv = sbx.wrap([exe, "-pdf", "-interaction=nonstopmode", "-halt-on-error", f"-outdir={build}", "main.tex"],
                    policy, allow_unsandboxed)
    try:
        r = subprocess.run(argv, cwd=str(folder), env=env, capture_output=True, text=True, timeout=240)
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "latexmk timed out"}
    pdf = build / "main.pdf"
    if r.returncode == 0 and pdf.exists():
        return {"ok": True, "pdf": str(pdf)}
    return {"ok": False, "error": (r.stdout + r.stderr)[-1500:]}
