"""§3.5: drafting and the review–rebuttal loop, then §4.2's post-hoc audit
(docs/paper/stages/05-drafting-peer-review.md, 07-integrity.md).

    draft:   a manuscript version holding the engine's results.tex/json → initial_drafter (writer)
    review:  peer_reviewer(manuscript) → score s in [1, 10]
    run_stage({version, review},
        critic = s >= threshold (8, App. A.2) → accept, else refine       a number, not an agent
        refine = rebuttal_planner → N_t rebuttal experiments (rebuttal_coder + harness, in parallel)
                 → results regenerated → paper_enhancer (writer) → review again
        limit N_peer, keep the last manuscript (§3.5; U-TOP-7 as data))
    audit:   reference_checker (search) and method_code_auditor (read-only); any finding goes to
             the paper_enhancer, never back to the auditor (A-INT-3)
"""
from __future__ import annotations

import json
from typing import Optional

from ..harness.harness import gain, summarize
from ..primitive import ACCEPT, REFINE, StageParams, run_stage
from ..runtime.agents import UnitFailed
from .coder import Baseline
from .common import Ctx
from .evolution import Core
from .manuscript import compile_pdf, manuscript_text, payload, write_results


def _results(ctx: Ctx, base: Baseline, core: Core, abl: list[dict], reb: list[dict]) -> dict:
    return payload(ctx.task, base, core, abl, reb)


def _seed_version(ctx: Ctx, name: str, p: dict) -> str:
    """An empty manuscript version holding only the verified results."""
    assert ctx.papers is not None
    if not ctx.papers.exists(name):
        src = ctx.run_dir / "scratch" / f"{name}.seed"
        src.mkdir(parents=True, exist_ok=True)
        write_results(src, p)
        ctx.papers.init_from(src, name, "verified results, generated by the engine")
    return name


def _refresh_results(ctx: Ctx, parent: str, name: str, p: dict) -> str:
    """A new version of `parent` whose results files are regenerated from result files."""
    assert ctx.papers is not None
    if ctx.papers.exists(name):
        return name
    tmp = ctx.papers.fresh(parent, name)
    write_results(tmp, p)
    ctx.papers.finalize(tmp, name, "results regenerated from the harness's result files")
    return name


def build(ctx: Ctx, name: str) -> dict:
    assert ctx.papers is not None
    rules = ctx.harness.integrity()
    report = compile_pdf(ctx.papers.path(name), ctx.run_dir / "builds" / name,
                         denied=rules["denied"], allow_unsandboxed=ctx.harness.allow_unsandboxed,
                         protected=tuple(rules["protected"]))
    ctx.event("pdf", version=name, ok=report["ok"])
    return report


def draft(ctx: Ctx, base: Baseline, core: Core, abl: list[dict], limitations: list[dict],
          references: list[dict], tag: str) -> str:
    assert ctx.papers is not None
    p = _results(ctx, base, core, abl, [])
    seed = _seed_version(ctx, f"{tag}.results", p)
    name = f"{tag}.draft"
    ctx.code(f"{tag}/draft", "initial_drafter", {
        "task_title": ctx.task.title, "paper": ctx.task.paper_text, "idea": core.idea,
        "limitations": limitations, "references": references, "results_tex": "results.tex",
        "results_json": json.dumps(p, indent=1, default=str)}, seed, name, on=ctx.papers)
    build(ctx, name)
    return name


def review(ctx: Ctx, key: str, version: str) -> dict:
    assert ctx.papers is not None
    return ctx.think(key, "peer_reviewer", {"manuscript": manuscript_text(ctx.papers.path(version))})


def rebuttal_round(ctx: Ctx, core: Core, rev: dict, tag: str) -> list[dict]:
    t = ctx.task
    n = ctx.L("n_t")
    plan = ctx.think(f"{tag}/plan", "rebuttal_planner", {
        "task_title": t.title, "idea": core.idea, "review": rev, "n_tasks": n})
    tasks = plan["tasks"][:n]

    def run(i_task: tuple[int, dict]) -> dict:
        i, task = i_task
        rid = f"R{i + 1}"
        name = f"{core.id}.{tag.replace('/', '-')}.{rid}"
        _, err = ctx.code(f"{tag}/{rid}/code", "rebuttal_coder", {
            "task_title": t.title, "rules": t.rules_text, "entrypoint": ctx.entrypoint_text(),
            "idea": core.idea, "task": task}, core.ws, name)
        result = ctx.evaluate(f"{tag}/{rid}/eval", name, "full")
        return {"id": f"{tag.split('/')[-1]}-{rid}", "task": task, "result": summarize(result),
                "delta_vs_full_method": gain(result, core.result), "agent_error": err}

    return ctx.map(run, list(enumerate(tasks)))


def writing_stage(ctx: Ctx, base: Baseline, core: Core, abl: list[dict], limitations: list[dict],
                  references: list[dict], pass_i: int) -> dict:
    """Returns {version, review, rebuttals, status}."""
    assert ctx.papers is not None
    tag = f"write/p{pass_i}"
    v0 = draft(ctx, base, core, abl, limitations, references, tag)
    start = {"version": v0, "review": review(ctx, f"{tag}/review/0", v0), "rebuttals": []}
    seen = [start]
    threshold = ctx.L("review_threshold")

    def critic(c: dict, i: int) -> tuple[str, dict]:
        return ("met" if int(c["review"]["score"]) >= threshold else "below"), c["review"]

    def refine(c: dict, rev: dict, i: int) -> dict:
        reb = c["rebuttals"] + rebuttal_round(ctx, core, rev, f"{tag}/rebut{i}")
        p = _results(ctx, base, core, abl, reb)
        staged = _refresh_results(ctx, c["version"], f"{tag}.r{i + 1}.results", p)
        name = f"{tag}.r{i + 1}"
        ctx.code(f"{tag}/enhance/{i}", "paper_enhancer", {
            "review": rev, "rebuttal_results_json": json.dumps(p, indent=1, default=str),
            "audit": "No audit findings yet: the integrity audit runs after the review loop."},
            staged, name, on=ctx.papers)
        build(ctx, name)
        new = {"version": name, "review": review(ctx, f"{tag}/review/{i + 1}", name), "rebuttals": reb}
        seen.append(new)
        return new

    cfg = ctx.stage("peer_review")
    outcome = run_stage(start, StageParams(
        "peer_review", critic, refine, {"met": ACCEPT, "below": REFINE}, limit=ctx.L("n_peer"),
        counting=cfg.get("counting", "refinements"), exhaustion="keep_last"))
    kept = outcome.candidate or seen[-1]
    if cfg.get("keep") == "best_score":       # U-TOP-7's other reading, as data
        kept = max(seen, key=lambda c: int(c["review"]["score"]))
    ctx.event("peer_review", status=outcome.status, score=int(kept["review"]["score"]),
              version=kept["version"], rounds=outcome.refinements)
    return {**kept, "status": outcome.status}


def audit(ctx: Ctx, base: Baseline, core: Core, abl: list[dict], written: dict, pass_i: int) -> tuple[dict, dict]:
    """§4.2's post-hoc checks on the manuscript. Returns (written, audit report)."""
    assert ctx.papers is not None
    tag = f"audit/p{pass_i}"
    integ = ctx.cfg.get("integrity", {})
    folder = ctx.papers.path(written["version"])
    report: dict = {"references": None, "method_code": None, "repaired": False}
    problems: list = []
    try:
        if integ.get("reference_check", True):
            bib = (folder / "references.bib").read_text() if (folder / "references.bib").exists() else ""
            if bib.strip():
                report["references"] = ctx.think(f"{tag}/references", "reference_checker", {"bibliography": bib})
                problems += [e for e in report["references"].get("entries", []) if e.get("status") != "verified"]
        if integ.get("method_code_audit", True):
            report["method_code"] = ctx.think(f"{tag}/method_code", "method_code_auditor", {
                "manuscript": manuscript_text(folder), "diff": ctx.diff(core.ws)}, readonly=ctx.ws.path(core.ws))
            if not report["method_code"].get("consistent", True):
                problems += report["method_code"].get("issues", [])
    except UnitFailed as e:
        report["error"] = e.error
        ctx.event("audit_error", error=e.error[:200])
    if problems:
        p = _results(ctx, base, core, abl, written["rebuttals"])
        name = f"{tag}.repaired"
        _, err = ctx.code(f"{tag}/repair", "paper_enhancer", {
            "review": {"summary": "No new review: this revision repairs only the integrity audit's findings."},
            "rebuttal_results_json": json.dumps(p, indent=1, default=str),
            "audit": {"problems": problems, "report": report}}, written["version"], name, on=ctx.papers)
        if err is None:
            build(ctx, name)
            written = {**written, "version": name}
            report["repaired"] = True
    ctx.event("audit", problems=len(problems), repaired=report["repaired"])
    return written, report
